### ISSUE TITLE
better font for the furigana

### ISSUE THREAD

**Issue by t33bags** [keve1227/furigana#2]
I've been using a resource pack that uses a more modern font for most languages that enhances the readability, including Japanese. I wonder if you can implement this font into your furigana resource pack as it especially helps with the readability of kana.

this is the base font used in some resource packs
https://www.curseforge.com/minecraft/texture-packs/modern-font-pack

default minecraft font
![image](https://github.com/keve1227/furigana/assets/159464557/1efe8041-a21a-4d11-81c0-b6ebea4f890f)
![image](https://github.com/keve1227/furigana/assets/159464557/e80c782e-8c8c-423e-8b22-7240bb541f86)

modernized minecraft font
![image](https://github.com/keve1227/furigana/assets/159464557/d2f666cf-992b-4983-a2a2-dfc023ff6f9b)
![image](https://github.com/keve1227/furigana/assets/159464557/b91dbc11-73b4-4020-ad1c-c7074d5046ef)

using both resource packs results in layered texts that make the furigana unreadable unless you use the larger gui scalings
![image](https://github.com/keve1227/furigana/assets/159464557/c5c8688d-0860-4743-8d56-2813d27814c9)
![image](https://github.com/keve1227/furigana/assets/159464557/b90cc49b-350c-4e69-827b-36d27ea705ff)

**Comment by CcMenta** [comment]
I think this is related to the rubi mod and not the furigana resource pack, so you should report on the rubi github page.
