### ISSUE TITLE
Resource pack does not work on 1.21.1

### ISSUE THREAD

**Issue by nicdgonzalez** [keve1227/furigana#4]
See following screenshots.

I made a [pull request](https://github.com/keve1227/rubi/pull/8) on the Rubi project to enable the client-side mod to run on Minecraft 1.21.1, but the furigana still wouldn't show so I assume there is something I need to do to fix the resource pack as well. If you could guide me in the right direction, I'd be happy to submit a pull request to fix this!

<div align="center">
<img src="https://github.com/user-attachments/assets/456669ce-882f-44bb-8e96-afe602ea6eda" alt="resource-pack-enabled" />
<caption>An in-game screenshot showing the resource pack is enabled</caption>
</div>

<div align="center">
<img src="https://github.com/user-attachments/assets/6af6ddd2-bd4d-402d-8423-93a419930c94" alt="no-furigana-displayed" />
<caption>An in-game screenshot showing there is no furigana above the kanji</caption>
</div>

**Comment by keve1227** [comment]
Did you select the language that the resource pack adds in Minecraft's language settings?

![language_settings](https://github.com/user-attachments/assets/b3d24e67-1658-4805-aa07-ce5d50433528)

**Comment by keve1227** [comment]
Either way, it seems to be fixed in the latest versions of [the mod](https://modrinth.com/mod/rubi) and [resource pack](https://modrinth.com/resourcepack/furigana).

**Comment by nicdgonzalez** [comment]
It works! I missed the part of the README that mentioned having to change the language, my bad. Thank you, I will close this issue now.
